packages:
  - packages/*
  - apps/*

ignoredBuiltDependencies:
  - canvas
  - core-js-pure
  - puppeteer

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
  - unrs-resolver
  - zenstack
