import type { TableRowData } from './columns';
import Decimal from 'decimal.js';

export const sampleRows: TableRowData[] = [
  {
    id: 'clx1abcde0001xyz1234abcd1',
    beneficiary: {
      id: 'b1',
      workId: 'W1001',
      name: 'Ali Ahmed',
      relationship: 'self',
    },
    requestedAmount: new Decimal(1000),
    reservedAmount: new Decimal(900),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc1',
      name: 'Tripoli Central',
      address: { city: 'Tripoli', country: 'Libya' },
      branchNum: 1,
    },
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'clx1abcde0002xyz1234abcd2',
    beneficiary: {
      id: 'b2',
      workId: 'W1002',
      name: 'Sara Omar',
      relationship: 'spouse',
    },
    requestedAmount: new Decimal(1500),
    reservedAmount: new Decimal(0),
    approvalStatus: 'rejected',
    reservationUtilizationStatus: 'unused',
    currency: 'USD',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc2',
      name: 'Benghazi North',
      address: { city: 'Benghazi', country: 'Libya' },
      branchNum: 2,
    },
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-06'),
  },
  {
    id: 'clx1abcde0003xyz1234abcd3',
    beneficiary: {
      id: 'b3',
      workId: 'W1003',
      name: 'Mohamed Saleh',
      relationship: 'child',
    },
    requestedAmount: new Decimal(2000),
    reservedAmount: new Decimal(2000),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'EUR',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc3',
      name: 'Misrata Clinic',
      address: { city: 'Misrata', country: 'Libya' },
      branchNum: 3,
    },
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'clx1abcde0004xyz1234abcd4',
    beneficiary: {
      id: 'b4',
      workId: 'W1004',
      name: 'Fatima Ali',
      relationship: 'parent',
    },
    requestedAmount: new Decimal(500),
    reservedAmount: new Decimal(500),
    approvalStatus: 'pending',
    reservationUtilizationStatus: 'pending',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc4',
      name: 'Zawiya Health',
      address: { city: 'Zawiya', country: 'Libya' },
      branchNum: 4,
    },
    createdAt: new Date('2024-04-12'),
    updatedAt: new Date('2024-04-13'),
  },
  {
    id: 'clx1abcde0005xyz1234abcd5',
    beneficiary: {
      id: 'b5',
      workId: 'W1005',
      name: 'Yousef Hassan',
      relationship: 'self',
    },
    requestedAmount: new Decimal(1200),
    reservedAmount: new Decimal(1000),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'unused',
    currency: 'USD',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc5',
      name: 'Sabha Medical',
      address: { city: 'Sabha', country: 'Libya' },
      branchNum: 5,
    },
    createdAt: new Date('2024-05-20'),
    updatedAt: new Date('2024-05-21'),
  },
  {
    id: 'clx1abcde0006xyz1234abcd6',
    beneficiary: {
      id: 'b6',
      workId: 'W1006',
      name: 'Layla Faraj',
      relationship: 'child',
    },
    requestedAmount: new Decimal(800),
    reservedAmount: new Decimal(800),
    approvalStatus: 'pending',
    reservationUtilizationStatus: 'pending',
    currency: 'EUR',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc6',
      name: 'Derna Hospital',
      address: { city: 'Derna', country: 'Libya' },
      branchNum: 6,
    },
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-02'),
  },
  {
    id: 'clx1abcde0007xyz1234abcd7',
    beneficiary: {
      id: 'b7',
      workId: 'W1007',
      name: 'Omar Khaled',
      relationship: 'spouse',
    },
    requestedAmount: new Decimal(3000),
    reservedAmount: new Decimal(2500),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc7',
      name: 'Ghadames Clinic',
      address: { city: 'Ghadames', country: 'Libya' },
      branchNum: 7,
    },
    createdAt: new Date('2024-07-10'),
    updatedAt: new Date('2024-07-11'),
  },
  {
    id: 'clx1abcde0008xyz1234abcd8',
    beneficiary: {
      id: 'b8',
      workId: 'W1008',
      name: 'Mona Nasser',
      relationship: 'parent',
    },
    requestedAmount: new Decimal(950),
    reservedAmount: new Decimal(950),
    approvalStatus: 'rejected',
    reservationUtilizationStatus: 'unused',
    currency: 'USD',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc8',
      name: 'Tobruk Health',
      address: { city: 'Tobruk', country: 'Libya' },
      branchNum: 8,
    },
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date('2024-08-16'),
  },
  {
    id: 'clx1abcde0009xyz1234abcd9',
    beneficiary: {
      id: 'b9',
      workId: 'W1009',
      name: 'Samir Fathi',
      relationship: 'self',
    },
    requestedAmount: new Decimal(1100),
    reservedAmount: new Decimal(1100),
    approvalStatus: 'pending',
    reservationUtilizationStatus: 'pending',
    currency: 'EUR',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc9',
      name: 'Al Bayda Medical',
      address: { city: 'Al Bayda', country: 'Libya' },
      branchNum: 9,
    },
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-09-02'),
  },
  {
    id: 'clx1abcde0010xyz1234abc10',
    beneficiary: {
      id: 'b10',
      workId: 'W1010',
      name: 'Huda Salem',
      relationship: 'spouse',
    },
    requestedAmount: new Decimal(1750),
    reservedAmount: new Decimal(1700),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc10',
      name: 'Sabratha Clinic',
      address: { city: 'Sabratha', country: 'Libya' },
      branchNum: 10,
    },
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-10-11'),
  },
  {
    id: 'clx1abcde0011xyz1234abc11',
    beneficiary: {
      id: 'b11',
      workId: 'W1011',
      name: 'Nabil Jamal',
      relationship: 'child',
    },
    requestedAmount: new Decimal(600),
    reservedAmount: new Decimal(0),
    approvalStatus: 'rejected',
    reservationUtilizationStatus: 'unused',
    currency: 'USD',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc11',
      name: 'Ajdabiya Health',
      address: { city: 'Ajdabiya', country: 'Libya' },
      branchNum: 11,
    },
    createdAt: new Date('2024-11-05'),
    updatedAt: new Date('2024-11-06'),
  },
  {
    id: 'clx1abcde0012xyz1234abc12',
    beneficiary: {
      id: 'b12',
      workId: 'W1012',
      name: 'Rania Khalifa',
      relationship: 'parent',
    },
    requestedAmount: new Decimal(2200),
    reservedAmount: new Decimal(2200),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'EUR',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc12',
      name: 'Gharyan Medical',
      address: { city: 'Gharyan', country: 'Libya' },
      branchNum: 12,
    },
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-02'),
  },
  {
    id: 'clx1abcde0013xyz1234abc13',
    beneficiary: {
      id: 'b13',
      workId: 'W1013',
      name: 'Khaled Musa',
      relationship: 'self',
    },
    requestedAmount: new Decimal(1300),
    reservedAmount: new Decimal(1200),
    approvalStatus: 'pending',
    reservationUtilizationStatus: 'pending',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc13',
      name: 'Zliten Clinic',
      address: { city: 'Zliten', country: 'Libya' },
      branchNum: 13,
    },
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-11'),
  },
  {
    id: 'clx1abcde0014xyz1234abc14',
    beneficiary: {
      id: 'b14',
      workId: 'W1014',
      name: 'Salma Idris',
      relationship: 'spouse',
    },
    requestedAmount: new Decimal(900),
    reservedAmount: new Decimal(900),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'USD',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc14',
      name: 'Kufra Health',
      address: { city: 'Kufra', country: 'Libya' },
      branchNum: 14,
    },
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-02-16'),
  },
  {
    id: 'clx1abcde0015xyz1234abc15',
    beneficiary: {
      id: 'b15',
      workId: 'W1015',
      name: 'Ayman Bashir',
      relationship: 'child',
    },
    requestedAmount: new Decimal(1600),
    reservedAmount: new Decimal(1500),
    approvalStatus: 'rejected',
    reservationUtilizationStatus: 'unused',
    currency: 'EUR',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc15',
      name: 'Murzuq Clinic',
      address: { city: 'Murzuq', country: 'Libya' },
      branchNum: 15,
    },
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date('2025-03-02'),
  },
  {
    id: 'clx1abcde0016xyz1234abc16',
    beneficiary: {
      id: 'b16',
      workId: 'W1016',
      name: 'Hassan Tarek',
      relationship: 'self',
    },
    requestedAmount: new Decimal(1800),
    reservedAmount: new Decimal(1700),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc16',
      name: 'Nalut Clinic',
      address: { city: 'Nalut', country: 'Libya' },
      branchNum: 16,
    },
    createdAt: new Date('2025-04-01'),
    updatedAt: new Date('2025-04-02'),
  },
  {
    id: 'clx1abcde0017xyz1234abc17',
    beneficiary: {
      id: 'b17',
      workId: 'W1017',
      name: 'Mariam Fawzi',
      relationship: 'spouse',
    },
    requestedAmount: new Decimal(2100),
    reservedAmount: new Decimal(2000),
    approvalStatus: 'pending',
    reservationUtilizationStatus: 'pending',
    currency: 'USD',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc17',
      name: 'Jalu Health',
      address: { city: 'Jalu', country: 'Libya' },
      branchNum: 17,
    },
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-11'),
  },
  {
    id: 'clx1abcde0018xyz1234abc18',
    beneficiary: {
      id: 'b18',
      workId: 'W1018',
      name: 'Samiya Bashir',
      relationship: 'parent',
    },
    requestedAmount: new Decimal(950),
    reservedAmount: new Decimal(900),
    approvalStatus: 'rejected',
    reservationUtilizationStatus: 'unused',
    currency: 'EUR',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc18',
      name: 'Ubari Medical',
      address: { city: 'Ubari', country: 'Libya' },
      branchNum: 18,
    },
    createdAt: new Date('2025-06-15'),
    updatedAt: new Date('2025-06-16'),
  },
  {
    id: 'clx1abcde0019xyz1234abc19',
    beneficiary: {
      id: 'b19',
      workId: 'W1019',
      name: 'Fathi Goma',
      relationship: 'child',
    },
    requestedAmount: new Decimal(1200),
    reservedAmount: new Decimal(1200),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc19',
      name: 'Bani Walid Clinic',
      address: { city: 'Bani Walid', country: 'Libya' },
      branchNum: 19,
    },
    createdAt: new Date('2025-07-01'),
    updatedAt: new Date('2025-07-02'),
  },
  {
    id: 'clx1abcde0020xyz1234abc20',
    beneficiary: {
      id: 'b20',
      workId: 'W1020',
      name: 'Aisha Salem',
      relationship: 'self',
    },
    requestedAmount: new Decimal(1400),
    reservedAmount: new Decimal(1300),
    approvalStatus: 'pending',
    reservationUtilizationStatus: 'pending',
    currency: 'USD',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc20',
      name: 'Sorman Health',
      address: { city: 'Sorman', country: 'Libya' },
      branchNum: 20,
    },
    createdAt: new Date('2025-08-10'),
    updatedAt: new Date('2025-08-11'),
  },
  {
    id: 'clx1abcde0021xyz1234abc21',
    beneficiary: {
      id: 'b21',
      workId: 'W1021',
      name: 'Mahmoud Idris',
      relationship: 'spouse',
    },
    requestedAmount: new Decimal(1600),
    reservedAmount: new Decimal(1500),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'EUR',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc21',
      name: 'Al Marj Clinic',
      address: { city: 'Al Marj', country: 'Libya' },
      branchNum: 21,
    },
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2025-09-02'),
  },
  {
    id: 'clx1abcde0022xyz1234abc22',
    beneficiary: {
      id: 'b22',
      workId: 'W1022',
      name: 'Rashid Musa',
      relationship: 'parent',
    },
    requestedAmount: new Decimal(2000),
    reservedAmount: new Decimal(1800),
    approvalStatus: 'rejected',
    reservationUtilizationStatus: 'unused',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc22',
      name: 'Tazerbo Health',
      address: { city: 'Tazerbo', country: 'Libya' },
      branchNum: 22,
    },
    createdAt: new Date('2025-10-10'),
    updatedAt: new Date('2025-10-11'),
  },
  {
    id: 'clx1abcde0023xyz1234abc23',
    beneficiary: {
      id: 'b23',
      workId: 'W1023',
      name: 'Nour Elhadi',
      relationship: 'child',
    },
    requestedAmount: new Decimal(900),
    reservedAmount: new Decimal(900),
    approvalStatus: 'pending',
    reservationUtilizationStatus: 'pending',
    currency: 'USD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc23',
      name: 'Ghat Clinic',
      address: { city: 'Ghat', country: 'Libya' },
      branchNum: 23,
    },
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2025-11-02'),
  },
  {
    id: 'clx1abcde0024xyz1234abc24',
    beneficiary: {
      id: 'b24',
      workId: 'W1024',
      name: 'Huda Fathi',
      relationship: 'self',
    },
    requestedAmount: new Decimal(1700),
    reservedAmount: new Decimal(1700),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'EUR',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc24',
      name: 'Qaminis Medical',
      address: { city: 'Qaminis', country: 'Libya' },
      branchNum: 24,
    },
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2025-12-02'),
  },
  {
    id: 'clx1abcde0025xyz1234abc25',
    beneficiary: {
      id: 'b25',
      workId: 'W1025',
      name: 'Salem Naji',
      relationship: 'spouse',
    },
    requestedAmount: new Decimal(1300),
    reservedAmount: new Decimal(1200),
    approvalStatus: 'pending',
    reservationUtilizationStatus: 'pending',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc25',
      name: 'Al Qubbah Health',
      address: { city: 'Al Qubbah', country: 'Libya' },
      branchNum: 25,
    },
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-01-11'),
  },
  {
    id: 'clx1abcde0026xyz1234abc26',
    beneficiary: {
      id: 'b26',
      workId: 'W1026',
      name: 'Fatma Khaled',
      relationship: 'parent',
    },
    requestedAmount: new Decimal(900),
    reservedAmount: new Decimal(900),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'USD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc26',
      name: 'Al Khums Clinic',
      address: { city: 'Al Khums', country: 'Libya' },
      branchNum: 26,
    },
    createdAt: new Date('2026-02-15'),
    updatedAt: new Date('2026-02-16'),
  },
  {
    id: 'clx1abcde0027xyz1234abc27',
    beneficiary: {
      id: 'b27',
      workId: 'W1027',
      name: 'Jamal Sassi',
      relationship: 'child',
    },
    requestedAmount: new Decimal(1600),
    reservedAmount: new Decimal(1500),
    approvalStatus: 'rejected',
    reservationUtilizationStatus: 'unused',
    currency: 'EUR',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc27',
      name: 'Tiji Health',
      address: { city: 'Tiji', country: 'Libya' },
      branchNum: 27,
    },
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-02'),
  },
  {
    id: 'clx1abcde0028xyz1234abc28',
    beneficiary: {
      id: 'b28',
      workId: 'W1028',
      name: 'Rania Omar',
      relationship: 'self',
    },
    requestedAmount: new Decimal(1800),
    reservedAmount: new Decimal(1700),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc28',
      name: 'Al Zawiya Clinic',
      address: { city: 'Al Zawiya', country: 'Libya' },
      branchNum: 28,
    },
    createdAt: new Date('2026-04-01'),
    updatedAt: new Date('2026-04-02'),
  },
  {
    id: 'clx1abcde0029xyz1234abc29',
    beneficiary: {
      id: 'b29',
      workId: 'W1029',
      name: 'Omar Fathi',
      relationship: 'spouse',
    },
    requestedAmount: new Decimal(2100),
    reservedAmount: new Decimal(2000),
    approvalStatus: 'pending',
    reservationUtilizationStatus: 'pending',
    currency: 'USD',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc29',
      name: 'Al Kufra Health',
      address: { city: 'Al Kufra', country: 'Libya' },
      branchNum: 29,
    },
    createdAt: new Date('2026-05-10'),
    updatedAt: new Date('2026-05-11'),
  },
  {
    id: 'clx1abcde0030xyz1234abc30',
    beneficiary: {
      id: 'b30',
      workId: 'W1030',
      name: 'Salma Naji',
      relationship: 'parent',
    },
    requestedAmount: new Decimal(950),
    reservedAmount: new Decimal(900),
    approvalStatus: 'rejected',
    reservationUtilizationStatus: 'unused',
    currency: 'EUR',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc30',
      name: 'Al Qatrun Medical',
      address: { city: 'Al Qatrun', country: 'Libya' },
      branchNum: 30,
    },
    createdAt: new Date('2026-06-15'),
    updatedAt: new Date('2026-06-16'),
  },
  {
    id: 'clx1abcde0031xyz1234abc31',
    beneficiary: {
      id: 'b31',
      workId: 'W1031',
      name: 'Hassan Musa',
      relationship: 'child',
    },
    requestedAmount: new Decimal(1200),
    reservedAmount: new Decimal(1200),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc31',
      name: 'Al Ajaylat Clinic',
      address: { city: 'Al Ajaylat', country: 'Libya' },
      branchNum: 31,
    },
    createdAt: new Date('2026-07-01'),
    updatedAt: new Date('2026-07-02'),
  },
  {
    id: 'clx1abcde0032xyz1234abc32',
    beneficiary: {
      id: 'b32',
      workId: 'W1032',
      name: 'Mona Idris',
      relationship: 'self',
    },
    requestedAmount: new Decimal(1400),
    reservedAmount: new Decimal(1300),
    approvalStatus: 'pending',
    reservationUtilizationStatus: 'pending',
    currency: 'USD',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc32',
      name: 'Al Maya Health',
      address: { city: 'Al Maya', country: 'Libya' },
      branchNum: 32,
    },
    createdAt: new Date('2026-08-10'),
    updatedAt: new Date('2026-08-11'),
  },
  {
    id: 'clx1abcde0033xyz1234abc33',
    beneficiary: {
      id: 'b33',
      workId: 'W1033',
      name: 'Yousef Fawzi',
      relationship: 'spouse',
    },
    requestedAmount: new Decimal(1600),
    reservedAmount: new Decimal(1500),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'EUR',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc33',
      name: 'Al Aziziya Clinic',
      address: { city: 'Al Aziziya', country: 'Libya' },
      branchNum: 33,
    },
    createdAt: new Date('2026-09-01'),
    updatedAt: new Date('2026-09-02'),
  },
  {
    id: 'clx1abcde0034xyz1234abc34',
    beneficiary: {
      id: 'b34',
      workId: 'W1034',
      name: 'Rania Goma',
      relationship: 'parent',
    },
    requestedAmount: new Decimal(2000),
    reservedAmount: new Decimal(1800),
    approvalStatus: 'rejected',
    reservationUtilizationStatus: 'unused',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc34',
      name: 'Al Qalaa Health',
      address: { city: 'Al Qalaa', country: 'Libya' },
      branchNum: 34,
    },
    createdAt: new Date('2026-10-10'),
    updatedAt: new Date('2026-10-11'),
  },
  {
    id: 'clx1abcde0035xyz1234abc35',
    beneficiary: {
      id: 'b35',
      workId: 'W1035',
      name: 'Samir Tarek',
      relationship: 'child',
    },
    requestedAmount: new Decimal(900),
    reservedAmount: new Decimal(900),
    approvalStatus: 'pending',
    reservationUtilizationStatus: 'pending',
    currency: 'USD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc35',
      name: 'Al Qardabiya Clinic',
      address: { city: 'Al Qardabiya', country: 'Libya' },
      branchNum: 35,
    },
    createdAt: new Date('2026-11-01'),
    updatedAt: new Date('2026-11-02'),
  },
  {
    id: 'clx1abcde0036xyz1234abc36',
    beneficiary: {
      id: 'b36',
      workId: 'W1036',
      name: 'Huda Bashir',
      relationship: 'self',
    },
    requestedAmount: new Decimal(1700),
    reservedAmount: new Decimal(1700),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'EUR',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc36',
      name: 'Al Zintan Medical',
      address: { city: 'Al Zintan', country: 'Libya' },
      branchNum: 36,
    },
    createdAt: new Date('2026-12-01'),
    updatedAt: new Date('2026-12-02'),
  },
  {
    id: 'clx1abcde0037xyz1234abc37',
    beneficiary: {
      id: 'b37',
      workId: 'W1037',
      name: 'Salem Fawzi',
      relationship: 'spouse',
    },
    requestedAmount: new Decimal(1300),
    reservedAmount: new Decimal(1200),
    approvalStatus: 'pending',
    reservationUtilizationStatus: 'pending',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc37',
      name: 'Al Msallata Health',
      address: { city: 'Al Msallata', country: 'Libya' },
      branchNum: 37,
    },
    createdAt: new Date('2027-01-10'),
    updatedAt: new Date('2027-01-11'),
  },
  {
    id: 'clx1abcde0038xyz1234abc38',
    beneficiary: {
      id: 'b38',
      workId: 'W1038',
      name: 'Fatma Goma',
      relationship: 'parent',
    },
    requestedAmount: new Decimal(900),
    reservedAmount: new Decimal(900),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'USD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc38',
      name: 'Al Shahhat Clinic',
      address: { city: 'Al Shahhat', country: 'Libya' },
      branchNum: 38,
    },
    createdAt: new Date('2027-02-15'),
    updatedAt: new Date('2027-02-16'),
  },
  {
    id: 'clx1abcde0039xyz1234abc39',
    beneficiary: {
      id: 'b39',
      workId: 'W1039',
      name: 'Jamal Idris',
      relationship: 'child',
    },
    requestedAmount: new Decimal(1600),
    reservedAmount: new Decimal(1500),
    approvalStatus: 'rejected',
    reservationUtilizationStatus: 'unused',
    currency: 'EUR',
    isBeneficiaryActiveWhenProcessed: false,
    healthCareCenter: {
      id: 'hc39',
      name: 'Al Abyar Health',
      address: { city: 'Al Abyar', country: 'Libya' },
      branchNum: 39,
    },
    createdAt: new Date('2027-03-01'),
    updatedAt: new Date('2027-03-02'),
  },
  {
    id: 'clx1abcde0040xyz1234abc40',
    beneficiary: {
      id: 'b40',
      workId: 'W1040',
      name: 'Rania Musa',
      relationship: 'self',
    },
    requestedAmount: new Decimal(1800),
    reservedAmount: new Decimal(1700),
    approvalStatus: 'approved',
    reservationUtilizationStatus: 'used',
    currency: 'LYD',
    isBeneficiaryActiveWhenProcessed: true,
    healthCareCenter: {
      id: 'hc40',
      name: 'Al Qubbah Clinic',
      address: { city: 'Al Qubbah', country: 'Libya' },
      branchNum: 40,
    },
    createdAt: new Date('2027-04-01'),
    updatedAt: new Date('2027-04-02'),
  },
];
